Iter13
justEngineer/go-metrics-service pull request #20
Opened 2024-04-21 17:44 UTC by justEngineer

2024-04-24 09:17 UTC, arttet requested changes
Please fix the `CodeCov` action

2024-04-25 11:02 UTC, justEngineer commented on internal/database/database.go
> +	err := d.Connections.Ping(context.Background())
done

2024-04-25 11:03 UTC, justEngineer commented on internal/database/database.go
> +		id      TEXT PRIMARY KEY,
replaced with VARCHAR (255)

2024-04-25 11:03 UTC, justEngineer commented on internal/database/database.go
> +	createTablesSQL = `
done

2024-04-25 11:04 UTC, justEngineer commented on internal/database/database.go
> +var retryTimeouts = [4]int{0, 1, 2, 3}
thank you for the advice. done

2024-04-25 11:04 UTC, justEngineer commented on internal/database/database.go
> +				time.Sleep(time.Duration(retryTimeouts[i]) * time.Second)
replaced with separate function "executeWithBackoff"

2024-04-26 15:27 UTC, arttet approved these changes

2024-05-26 20:05 UTC, merged